[colors.bright]
black =      "#201942"
red =        "#ff815a"
green =      "#d8816c"
yellow =     "#ffb07e"
blue =       "#565ea1"
magenta =    "#be8bc9"
cyan =       "#8176be"
white =      "#fdfcff"

[colors.cursor]
text =      "#0f0c1e"
cursor =    "#c3c2c6"

[colors.normal]
black =      "#0f0c1e"
red =        "#BC6B53"
green =      "#9A6B60"
yellow =     "#D88F72"
blue =       "#4C5073"
magenta =    "#8A788E"
cyan =       "#6C6787"
white =      "#c3c2c6"

[colors.primary]
background = "#0f0c1e"
foreground = "#fdfcff"
