# Shell variables
# Generated by 'wal'
wallpaper="$HOME/.cache/wallpaper.jpg"

# Special
background='#0f0c1e'
foreground='#fdfcff'
cursor='#fdfcff'

# Colors
color0='#0f0c1e'
color1='#BC6B53'
color2='#9A6B60'
color3='#D88F72'
color4='#4C5073'
color5='#8A788E'
color6='#6C6787'
color7='#c3c2c6'
color8='#201942'
color9='#ff815a'
color10='#d8816c'
color11='#ffb07e'
color12='#565ea1'
color13='#be8bc9'
color14='#8176be'
color15='#fdfcff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
