# Shell variables
# Generated by 'wal'
wallpaper="./.cache/wallpaper.jpg"

# Special
background='#160f18'
foreground='#fff6ed'
cursor='#fff6ed'

# Colors
color0='#160f18'
color1='#8F729F'
color2='#64679F'
color3='#9FA293'
color4='#515EAF'
color5='#CA7193'
color6='#6D928A'
color7='#e4cec7'
color8='#322137'
color9='#bf82e0'
color10='#7176df'
color11='#dae6ab'
color12='#586ef4'
color13='#ff7eba'
color14='#7dcebc'
color15='#fff6ed'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
